[package]
name = "kalkoto-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
itertools = "0.13.0"
tempdir = "0.3.7"
thiserror = "2.0.9"
toml = "0.8.19"
serde = { version = "1.0", features = ["derive"] }
crossterm = "0.28.1"
rayon = "1.10.0"
pyo3 = "0.27.1"
pyo3-ffi = "0.27.1"


